name: Dartle CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.19.0, stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Generate model
        run: dart dartle.dart generate
      - name: Test
        run: dart dartle.dart